services:

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      -  "3000:80"  
    depends_on:
      - backend
  backend:
    build:
      context: ./backend_api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
